spring:
  application:
    name: userauthentication-service
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/keepnote
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
