spring:
  data:
    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
      database: keepnote
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/