spring:
  application:
    name: zuul-api-gateway-server
server:
  port: 8765
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    users:
      path: /api/**
      sensitiveHeaders: Authorization